"""add_emotion_scenario_tables

Revision ID: 27583c10e473
Revises: 996b01c63f7f
Create Date: 2026-06-17 14:00:14.914352

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '27583c10e473'
down_revision: Union[str, None] = '996b01c63f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emotion_key', sa.String(length=50), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('ix_emotion_logs_id', 'id')
    )
    op.create_table('scenario_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('ix_scenario_completions_id', 'id')
    )
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'parent', 'specialist', name='userrole'),
               type_=sa.Enum('admin', 'parent', 'specialist', name='userrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'parent', 'specialist', name='userrole', native_enum=False),
               type_=postgresql.ENUM('admin', 'parent', 'specialist', name='userrole'),
               existing_nullable=False)
    op.drop_table('scenario_completions')
    op.drop_table('emotion_logs')
    # ### end Alembic commands ###
